# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Two method for Lasso
#'
#'@param y the response vector
#'@param X the design matrix
#'@param lambda the penalty parameter
#'@param c the precision parameter
#'@return the estimated beta
#'@example
#'require(CDLasso)
#'X=matrix(c(1,1,-1,-1),nrow=2)
#'y=c(2,-2)
#'lambda=1
#'c=0.01
#'CDLasso(y,X,lambda,c)
CDLasso <- function(y, X, lambda, c) {
    .Call('_Lasso_CDLasso', PACKAGE = 'Lasso', y, X, lambda, c)
}

#'Two method for Lasso
#'
#'@param y the response vector
#'@param X the design matrix
#'@param lambda the penalty parameter
#'@param c the precision parameter
#'@return the estimated beta
#'@example
#'require(POLasso)
#'X=matrix(c(1,1,-1,-1),nrow=2)
#'y=c(2,-2)
#'lambda=1
#'c=0.01
#'POLasso(y,X,lambda,c)
POLasso <- function(y, X, lambda, c) {
    .Call('_Lasso_POLasso', PACKAGE = 'Lasso', y, X, lambda, c)
}

